### PR TITLE
issue: randomly executing onFinishCallback

### PR DESCRIPTION
**Pull request by farhanlatheef**
onFinishCallback is executed randomly because onFinishCallback is used as variable not as function. if is fixed

### CODE REVIEW

**Comment by adamalbrecht** [comment]
@novarac23 Can you take a look at this? I haven't been in Angular land lately, so I forget some of the directive syntax stuff.

and @farhanlatheef, can you also commit the compiled versions in the `dist/` directory? Thanks for the pull request!

**Comment by novarac23** [comment]
@adamalbrecht Yep I am gonna take a look at it, thanks for letting me know! 

@farhanlatheef Also can you provide a bit more context about the issue ? When did it occur ? Thanks! :)

**Comment by farhanlatheef** [comment]
@novarac23  onFinishCallback is a callback only supposed to execute when tour is ended or closed, but it get executed many times in the beginning itself

**Comment by novarac23** [comment]
@farhanlatheef Ok cool thanks mate! Can you commit compiled version of `dist/` directory ? 💃

**Comment by farhanlatheef** [comment]
@novarac23 just did

**Comment by novarac23** [comment]
Merged into master! Thanks for doing a PR mate! 🍻

**Pull request closed without merging**
